service: bot-inactivity

provider:
  name: google
  runtime: python37
  region: us-central1
  stage: dev
  project: adachatbot-4647e
  credentials: ~/.gcloud/keyfile.json
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: '~/.gcloud/keyfile.json'

plugins:
  - serverless-google-cloudfunctions

functions:
  inactivity:
    handler: inactivity
    events:
      - http: inactivity
  